// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sakjpflpqfadtclipfsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNha2pwZmxwcWZhZHRjbGlwZnNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjMxMzcsImV4cCI6MjA2MTEzOTEzN30.OwXgr9v0L3f2M9cMKl47TR6Oz0Clcb3nxWwqiU7Ek6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);